### PR TITLE
Fixes #294 - selectively exclude hidden directories

### LINKED ISSUE #294: Kotlin files in dot directories not indexed
Teamcity kotlin files [typically live in _.teamcity/_](https://www.jetbrains.com/help/teamcity/kotlin-dsl.html#Project+Settings+Structure).

Example:
```
$ git clone https://github.com/tekumara/teamcity-kotlin-example
$ tree -a teamcity-kotlin-example
teamcity-kotlin-example
....
└── .teamcity
    ├── common.kt
    ├── pom.xml
    └── settings.kts
```

When I open _teamcity-kotlin-example/_ in vscode, the Kotlin LS doesn't add the teamcity kotlin files to the source path:
```
[Info  - 6:38:39 PM] main      Adding script definitions [ScriptTemplateWithArgs]
[Info  - 6:38:39 PM] main      Kotlin Language Server: Version 1.1.1
[Info  - 6:38:39 PM] main      Connected to client
[Info  - 6:38:39 PM] async0    Adding workspace folder teamcity-kotlin-example
[Info  - 6:38:40 PM] async0    Adding 0 files under /tmp/teamcity-kotlin-example to source path
...
```
And therefore Go to Definition, hover etc. in settings.kts doesn't work, eg: on line 39 `open class BaseBuildType() : BuildType()`

Other scenarios:
1. open  _teamcity-kotlin-example/.teamcity_ in vscode. The kotlin files will be indexed, but I can no longer work on the other files in the repository at the same time.
1. rename _.teamcity/_ to _teamcity/_ and open the root folder (ie: _teamcity-kotlin-example/_). The Kotlin LS correctly adds the files to the source path on startup:
```
[Info  - 8:56:12 PM] async0    Adding workspace folder teamcity-kotlin-example
[Info  - 8:56:12 PM] async0    Adding .../teamcity/common.kt, .../teamcity/settings.kts under /tmp/teamcity-kotlin-example to source path
```

vscode extension: fwcd.kotlin v0.2.22

### PR DESCRIPTION
**Pull request by Tony-Sol**
Fixes #294 (partly): Selectively exclude hidden directories instead of all hidden files and dirs (mainly, to make it easier to work with [Teamcity Kotlin DSL](https://www.jetbrains.com/help/teamcity/kotlin-dsl.html#Project+Settings+Structure))

### CODE REVIEW

File: shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt [hunk 1]
```diff
@@ -13,8 +13,10 @@ class SourceExclusions(
     private val workspaceRoots: Collection<Path>,
     private val scriptsConfig: ScriptsConfiguration
 ) {
-	val excludedPatterns = (listOf(
-        ".*", "bazel-*", "bin", "build", "node_modules", "target"
+    val excludedPatterns = (listOf(
+        ".git", ".hg", ".svn",                                                      // Version control systems
+        ".idea", ".idea_modules", ".vs", ".vscode", ".code-workspace", ".settings", // IDEs
+        "bazel-*", "bin", "build", "node_modules", "target",                        // Build systems
```
Comment (fwcd) [inline shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt:19]: Hm, I would rather integrate with .gitignore or a custom file (e.g. .klsignore) than adding to this ever-growing list of hardcoded directories... my worry is that directory names like `target` are already so generic, that there might be non-Maven-projects that place their source code there, for example

Comment (fwcd) [reply shared/src/main/kotlin/org/javacs/kt/SourceExclusions.kt:19]: Yeah I agree, in the long term we have got to fix this... but for now this fix shouldn't hurt.

**Comment by stevenrchun** [comment]
I've attempted that "proper solution" here https://github.com/fwcd/kotlin-language-server/pull/574 which is ready for review.
