### PR TITLE
Fix whitespace in path crashes the server

### LINKED ISSUE #200: Whitespace in path crashes the server.
The server won't start if path to current folder contains whitespaces.

```
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index ...: file:///.../some folder/.../
	at java.net.URI.create(Unknown Source)
	at org.javacs.kt.util.URIsKt.parseURI(URIs.kt:14)
	at org.javacs.kt.KotlinLanguageServer.initialize(KotlinLanguageServer.kt:73)
	... 16 more
```

### PR DESCRIPTION
**Pull request by alisabzevari**
To fix #200,

This PR fixes the whitespace issue that results crashing the server at initialization phase.

### CODE REVIEW

File: shared/src/main/kotlin/org/javacs/kt/util/URIs.kt [hunk 1]
```diff
@@ -1,8 +1,9 @@
 package org.javacs.kt.util
 
-import java.nio.charset.StandardCharsets
+import org.eclipse.core.runtime.URIUtil
```
Comment (fwcd) [inline shared/src/main/kotlin/org/javacs/kt/util/URIs.kt:3]: Is there a way to get this URI conversion behavior without pulling in a new dependency on the Eclipse runtime?

Comment (alisabzevari) [reply shared/src/main/kotlin/org/javacs/kt/util/URIs.kt:3]: I tried to write the conversion code myself but then I realized URI are more complicated that I thought (Like Datetime :wink:). This is the source code for [`URIUtil.fromString`](https://github.com/eclipse/rt.equinox.bundles/blob/master/bundles/org.eclipse.equinox.common/src/org/eclipse/core/runtime/URIUtil.java#L128-L150).

Comment (fwcd) [reply shared/src/main/kotlin/org/javacs/kt/util/URIs.kt:3]: Are there other characters than spaces that we would have to handle? If not, we just do a replacement of spaces by `%20`.

This seems to be a [somewhat common issue](https://stackoverflow.com/questions/2593214/android-how-to-parse-url-string-with-spaces-to-uri-object).
